apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cloudlab
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      # worker 无公网，业务固定调度到 master
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      imagePullSecrets:
        - name: acr-pull
      containers:
        - name: api
          # ACR VPC 镜像；发版更新 tag 见 README 9.5（kubectl set image 或改本行）
          image: crpi-6zjjswgvnui3es9q-vpc.cn-hangzhou.personal.cr.aliyuncs.com/zhou554_cloudlab/api:e2aaf6c8191b852d742b88ef3f613d39b16b432b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: cloudlab-config
            - secretRef:
                name: cloudlab-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
